#!/bin/sh

#miZy-openwrt-sdk config

arch=imx6
arch=sunxi

ow_sdk=OpenWrt-SDK-${arch}_gcc-5.3.0_musl-1.1.16_eabi.Linux-x86_64
ow_tc=OpenWrt-Toolchain-${arch}_gcc-5.3.0_musl-1.1.16_eabi.Linux-x86_64
ow_rootfs=openwrt-$arch-generic-rootfs.tar.gz
#ow_base=https://downloads.openwrt.org/snapshots/trunk/$arch/generic
ow_base=https://archive.openwrt.org/snapshots/trunk/sunxi/generic/
download_base=https://github.com/hyphop/pkg/releases/download/mirror/

ow_sdk_squash=$ow_sdk.squashfs
squash_src=../$ow_sdk.squashfs

src=openwrt
dl=dl
bin=bin

#tc=toolchain-arm_cortex-a8+vfpv3_gcc-5.3.0_musl-1.1.16_eabi
tc=toolchain-arm_cortex-a8.vfpv3_gcc-5.3.0_musl-1.1.16_eabi

tc_oname=$tc
#tc=${tc/+/.}
tc_squash_name=$tc.squashfs
tc_squash=../$tc.squashfs
tc_dir=../$tc

tc_ow=$tc_oname
tc_dir_ow=$src/staging_dir/$tc_ow

make_args="-j 32"   # buggy
make_args=""		#	

feeds=$src/scripts/feeds

trys="1 2 3"      # fix make -jX fails
trys="1"

tmp=tmp