#!/bin/sh

dir=$1

[ "$dir" = "" ] && dir=fake.bin

echo "[i] download feeds source $dir"

http=./tools/http
perl -c $http 2>/dev/null || {

    echo "[e] run / try to fix it";
    cpan -fi HTTP::Daemon

}

dir=$dir $http

