#!/bin/sh

## hyphop ##

## one-line command - easy make 

usage() { echo "USAGE:

    wget https://raw.githubusercontent.com/hyphop/miZy-openwrt-sdk/master/make_it_easy -O- | sh -

"
}

[ -p /tmp/zero_builder ] || mkdir -p /tmp/zero_builder 
cd /tmp/zero_builder || exit 1

git clone https://github.com/hyphop/miZy-openwrt-sdk.git
cd miZy-openwrt-sdk  || exit 1

./openwrt.sdk.download
./openwrt.sdk.prepare
./openwrt.sdk.feeds


